# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: rpg stuff | blog 
email: 
description: > # this means to ignore newlines until "baseurl:"
  You have found the blog of Nathan Hare. Here you'll find my musings on various
  topics such as Tabletop RPGs (specifically Fate Core) and my web development 
  projects. The other pages on this site are resources to be used along with 
  tabletop RPGs. Thanks for reading, and let me know what you think!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rpg.nathanhare.net" # the base hostname & protocol for your site
excerpt_separator: <!--more-->
twitter_username: treetrnk 
github_username:  treetrnk

# Build settings
redirects: yes
markdown: kramdown
