# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: rpg stuff | blog 
email: 
description: > # this means to ignore newlines until "baseurl:"
  You have found the blog of Nathan Hare. Here you'll find my musings on various
  topics such as Tabletop RPGs (specifically Fate Core) and my web development 
  projects. The other pages on this site are resources to be used along with 
  tabletop RPGs. I have handcoded them all myself in my free time, so if you 
  enjoy them and want to see more of them, click the Donate button and buy me a 
  drink. Thanks for reading!
baseurl: "/rpg/blog" # the subpath of your site, e.g. /blog
url: "http://nathanhare.net/" # the base hostname & protocol for your site
twitter_username: treetrnk 
github_username:  treetrnk

# Build settings
markdown: kramdown
