# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nate the GM 
email: Coming soon
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my blog, where I state my thoughts as an RPG game master and web 
  developer. My RPG of choice is Fate Core and I use my skills in web 
  development to build tools for RPGs in my free time. Stick around if it 
  sounds interesting!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nathanhare.net" # the base hostname & protocol for your site
twitter_username: treetrnk 
github_username:  treetrnk

# Build settings
markdown: kramdown
